### ISSUE TITLE
Cannot submit a review

### ISSUE THREAD

**Issue by zeizyy** [thecourseforum/theCourseForum#46] opened 2015-02-28 18:18 UTC
The website complains that 
    Professor rating must be greater than or equal to 1
    Enjoyability must be greater than or equal to 1
    Difficulty must be greater than or equal to 1
    Recommend must be greater than or equal to 1
However all the fields are greater than 1

**Comment by ama4tf** [comment] 2015-02-28 19:31
Can you append a screenshot or a specific url and actions to recreate the bug?

**Comment by jt4uc** [comment] 2015-04-02 04:09
Duplicate of #64

**Closed by jt4uc** 2015-04-02 04:09 UTC
Labels: Bug, Medium, story-points-1
