### ISSUE TITLE
Number of credits does not update when a class is deleted from the scheduler list

### ISSUE THREAD

**Issue by cyt3ea** [thecourseforum/theCourseForum#80] opened 2015-03-23 04:43 UTC
Add a class, select sections.
Delete the class and the number of credits is not updated.

**Comment by aw3as** [comment] 2015-03-31 00:30
duplicate of #90 fixed via c3053f674240e83984203254b051b0a1f59d3347

**Closed by aw3as** 2015-03-31 00:30 UTC
Labels: Bug, Dev, Polish
